from enum import Enum


class MismatchType(str, Enum):
    """Types of mismatches in GST reconciliation."""
    
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    TAX_AMOUNT_MISMATCH = "TAX_AMOUNT_MISMATCH"
    MISSING_IN_GSTR2B = "MISSING_IN_GSTR2B"
    MISSING_IN_GSTR1 = "MISSING_IN_GSTR1"
    MISSING_IN_PURCHASE_REGISTER = "MISSING_IN_PURCHASE_REGISTER"
    GSTIN_MISMATCH = "GSTIN_MISMATCH"
    DATE_MISMATCH = "DATE_MISMATCH"
    INVOICE_NUMBER_MISMATCH = "INVOICE_NUMBER_MISMATCH"
    TAX_RATE_MISMATCH = "TAX_RATE_MISMATCH"
    HSN_CODE_MISMATCH = "HSN_CODE_MISMATCH"
    DUPLICATE_ENTRY = "DUPLICATE_ENTRY"
    IRN_MISMATCH = "IRN_MISMATCH"
    REVERSE_CHARGE_MISMATCH = "REVERSE_CHARGE_MISMATCH"
