"""IRN (Invoice Reference Number) value object."""

import re
from dataclasses import dataclass


@dataclass(frozen=True)
class IRN:
    """
    IRN (Invoice Reference Number) value object for e-Invoices.
    64-character alphanumeric hash generated by IRP.
    """
    
    value: str
    
    IRN_PATTERN = re.compile(r'^[a-f0-9]{64}$', re.IGNORECASE)
    
    def __post_init__(self):
        """Validate IRN format."""
        if not self.is_valid():
            raise ValueError(f"Invalid IRN format: {self.value}")
    
    def is_valid(self) -> bool:
        """Check if IRN is valid."""
        if not self.value or len(self.value) != 64:
            return False
        return bool(self.IRN_PATTERN.match(self.value))
    
    def __str__(self) -> str:
        return self.value
    
    def __eq__(self, other) -> bool:
        if not isinstance(other, IRN):
            return False
        return self.value.lower() == other.value.lower()
    
    def __hash__(self) -> int:
        return hash(self.value.lower())
